spring:
  application:
    name: Citronix

  datasource:
    url: jdbc:postgresql://localhost:5432/Citronix
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jta:
    enabled: true